version: '3'
services:
  grafana:
    image: "grafana/grafana"
    environment:
      GF_INSTALL_PLUGINS: simpod-json-datasource 0.3.0,novatec-sdg-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
volumes:
  grafana-storage: