version: '3'
services:
  postgresql:
    image: "postgres"
    env_file:
      - postgresql.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  database-data: