version: '3'
services:
  postgresql:
    image: "postgres" # use latest official postgres version
    env_file:
      - postgresql.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
volumes:
  database-data: # named volumes can be managed easier using docker-compose