version: '3'
services:
  timescale:
    image: "timescale/timescaledb:latest-pg14"
    env_file:
      - timescale.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  database-data: