on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: p4skal
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "bootBuildImage --imageName p4skal/hawk-service:${{ github.ref_name }}"
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Add latest tag
        run: "docker tag p4skal/hawk-service:${{ github.ref_name }} p4skal/hawk-service:latest"
      - name: Push to DockerHub
        run: docker push p4skal/hawk-service --all-tags